# Generated by Django 4.1 on 2024-05-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panne", "0003_panne_immobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devis",
            old_name="date",
            new_name="date_devis",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="cout",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="type",
        ),
        migrations.AddField(
            model_name="devis",
            name="cout_devis",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="cout_reparation",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_reparation",
            field=models.DateField(null=True),
        ),
    ]
