# Generated by Django 4.1 on 2024-05-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20, null=True)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=100, null=True)),
                ("date_naissance", models.DateField(null=True)),
                ("lieu_naissance", models.CharField(max_length=100, null=True)),
                (
                    "poste",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.poste",
                    ),
                ),
            ],
        ),
    ]
