# Generated by Django 4.1 on 2024-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="description",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
