# Generated by Django 5.0.6 on 2024-06-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicule", "0005_vehicule_desactivate"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicule",
            name="imei",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="vehicule",
            name="desactivate",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
