# Generated by Django 4.1 on 2024-06-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicule", "0004_remove_vehicule_client_vehicule_proprio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type_entretien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.TextField()),
                ("duree_moyenne", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Entretien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("date", models.DateField()),
                ("nombre", models.FloatField(null=True)),
                ("montant", models.FloatField(null=True)),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entretien.type_entretien",
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicule.vehicule",
                    ),
                ),
            ],
        ),
    ]
