# Generated by Django 4.1 on 2024-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denomination", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("bp", models.CharField(max_length=50)),
            ],
        ),
    ]
