# Generated by Django 4.1 on 2024-05-28 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicule", "0002_categorie_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consommation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("montant", models.FloatField(null=True)),
                (
                    "vehicule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicule.vehicule",
                    ),
                ),
            ],
        ),
    ]
