# Generated by Django 4.1 on 2024-05-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicule", "0002_categorie_description"),
        ("employe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateField()),
                ("fin", models.DateField(null=True)),
                ("depart", models.CharField(max_length=100, null=True)),
                ("destination", models.CharField(max_length=100, null=True)),
                (
                    "vehicule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicule.vehicule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=100)),
                ("date", models.DateField(null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mission.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mission.mission",
                    ),
                ),
            ],
        ),
    ]
