# Generated by Django 4.1 on 2024-05-27 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Parcours",
            new_name="Escale",
        ),
    ]
