# Generated by Django 4.1 on 2024-05-27 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mission", "0002_rename_parcours_escale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="escale",
            old_name="ville",
            new_name="destination",
        ),
    ]
